### PR TITLE
Feature/changes for the standard

### PR DESCRIPTION
**Pull request by obalandi**
## WHAT

Ontologies are customized based on the standard. Unused code and templates are removed. Documentation and documentation generation scripts are added.

## WHY

The changes were necessary to improve the user-friendliness of the repository and conformity with the standards.

### CODE REVIEW

**Review by drcgjung — APPROVED** [review]
guess we need to run the merge/generate markdown workflow after these changes?

**Review by drcgjung — CHANGES_REQUESTED** [review]
the .github/workflow/build.yaml does not work anymore as there are no more java files/maven projects and test reports. We should delete it.

**Comment by arnoweiss** [comment]
Are we sacrificing resolvability of IRIs by declaring resources for a single namespace (`https://w3id.org/catenax/taxonomy#`) in two separate files (`asset_taxonomy.ttl` and `core_taxonomy.ttl`)? Or do they get merged together in a pipeline somewhere?

**Comment by obalandi** [comment]
Hi @arnoweiss. They will be merged (see ontology_tools/merger.py) and only the taxonomy in the main directory will be published on w3id.org/catenax.

**Review by drcgjung — APPROVED** [review]
LGTM

**Pull request merged**
